<?php
session_start(); require 'db_connection.php'; require_once 'helpers.php'; require_admin(); $conn=OpenCon();
$filter=$_GET['filter']??'all'; $ticketId=$_GET['ticket_id']??''; $userId=$_GET['user_id']??''; $q=trim($_GET['q']??'');
$sql="SELECT t.*,u.first_name,u.last_name,u.email FROM tickets t JOIN users u ON u.id=t.user_id WHERE 1=1"; $types=''; $params=[];
if($filter==='open'||$filter==='closed'){ $sql.=" AND t.status=?"; $types.='s'; $params[]=$filter; }
if($ticketId!==''){ $sql.=" AND t.id=?"; $types.='i'; $params[]=(int)$ticketId; }
if($userId!==''){ $sql.=" AND t.user_id=?"; $types.='i'; $params[]=(int)$userId; }
if($q!==''){ $like="%$q%"; $sql.=" AND (u.first_name LIKE ? OR u.last_name LIKE ? OR u.email LIKE ?)"; $types.='sss'; array_push($params,$like,$like,$like); }
$sql.=" ORDER BY t.created_at DESC"; $stmt=$conn->prepare($sql); if($params){$stmt->bind_param($types,...$params);} $stmt->execute(); $tickets=$stmt->get_result();
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Tickets</title><link rel="stylesheet" href="css/style.css"></head><body><?php include 'navbar.php'; ?><div class="admin-container"><h2>Tickets Management</h2><form method="get" class="card"><div class="grid"><label>Status<select name="filter"><option value="all" <?=$filter==='all'?'selected':''?>>All</option><option value="open" <?=$filter==='open'?'selected':''?>>Open</option><option value="closed" <?=$filter==='closed'?'selected':''?>>Closed</option></select></label><label>Ticket #<input type="number" name="ticket_id" value="<?=e($ticketId)?>"></label><label>Customer ID<input type="number" name="user_id" value="<?=e($userId)?>"></label><label>Name/Email<input name="q" value="<?=e($q)?>"></label></div><button>Search</button> <a class="btn" href="admin_tickets.php">Reset</a></form><br><table><tr><th>Ticket #</th><th>Customer ID</th><th>Customer</th><th>Email</th><th>Status</th><th>Created</th><th>Closed</th><th>Action</th></tr><?php while($t=$tickets->fetch_assoc()):?><tr><td><?=(int)$t['id']?></td><td><?=(int)$t['user_id']?></td><td><?=e($t['first_name'].' '.$t['last_name'])?></td><td><?=e($t['email'])?></td><td><span class="badge <?=e($t['status'])?>"><?=e($t['status'])?></span></td><td><?=e($t['created_at'])?></td><td><?=e($t['closed_at']??'-')?></td><td><a href="admin_ticket_view.php?id=<?=(int)$t['id']?>">View</a></td></tr><?php endwhile;?></table></div></body></html>
