<?php
session_start(); require 'db_connection.php'; require_once 'helpers.php'; require_admin(); $conn=OpenCon();
if(isset($_POST['update_status'])){
    $orderId=(int)$_POST['order_id']; $orderType=$_POST['order_type']==='pickup'?'pickup':'delivery'; $status=in_array($_POST['status'],['processing','ready','completed'])?$_POST['status']:'processing'; $carrierId=($_POST['carrier_id']??'')!==''?(int)$_POST['carrier_id']:null;
    if($orderType==='delivery') { if($carrierId===null){$stmt=$conn->prepare("UPDATE deliveries SET status=?, carrier_id=NULL, updated_at=NOW() WHERE order_id=?"); $stmt->bind_param("si",$status,$orderId);} else {$stmt=$conn->prepare("UPDATE deliveries SET status=?, carrier_id=?, updated_at=NOW() WHERE order_id=?"); $stmt->bind_param("sii",$status,$carrierId,$orderId);} $stmt->execute(); }
    $stmt=$conn->prepare("UPDATE orders SET order_status=? WHERE id=?"); $stmt->bind_param("si",$status,$orderId); $stmt->execute();
    $info=$conn->prepare("SELECT o.user_id,o.total_price,u.email,u.first_name FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=?"); $info->bind_param("i",$orderId); $info->execute(); $order=$info->get_result()->fetch_assoc();
    if($order) send_html_mail($order['email'],"Order #$orderId Status Update","<h2>Order Status Updated</h2><p>Hello ".e($order['first_name']).", your order is now <b>".e($status)."</b>.</p>");
    if($status==='completed' && $order){ $check=$conn->prepare("SELECT id FROM closed_orders WHERE order_id=?"); $check->bind_param("i",$orderId); $check->execute(); if($check->get_result()->num_rows===0){$ins=$conn->prepare("INSERT INTO closed_orders (order_id,user_id,total_price,status,closed_at) VALUES (?,?,?,'completed',NOW())"); $ins->bind_param("iid",$orderId,$order['user_id'],$order['total_price']); $ins->execute();} $del=$conn->prepare("DELETE FROM deliveries WHERE order_id=?"); $del->bind_param("i",$orderId); $del->execute(); }
    redirect('admin_deliveries.php');
}
$orders=$conn->query("SELECT o.id,o.order_type,o.order_status,o.total_price,u.first_name,u.email FROM orders o JOIN users u ON u.id=o.user_id WHERE o.order_status!='completed' ORDER BY o.id DESC");
$carriers=$conn->query("SELECT * FROM carriers ORDER BY name")->fetch_all(MYSQLI_ASSOC);
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Manage Orders</title><link rel="stylesheet" href="css/style.css"></head><body><?php include 'navbar.php'; ?><div class="admin-container"><h2>Manage Orders & Deliveries</h2><table><tr><th>Order #</th><th>User</th><th>Email</th><th>Total</th><th>Type</th><th>Status</th><th>Action</th><th>Details</th></tr><?php while($r=$orders->fetch_assoc()):?><tr><form method="post"><td><?=(int)$r['id']?></td><td><?=e($r['first_name'])?></td><td><?=e($r['email'])?></td><td>$<?=number_format((float)$r['total_price'],2)?></td><td><?=e(strtoupper($r['order_type']))?></td><td><select name="status"><?php foreach(['processing','ready','completed'] as $s):?><option value="<?=$s?>" <?=$r['order_status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></td><td><?php if($r['order_type']==='delivery'):?><select name="carrier_id"><option value="">No carrier</option><?php foreach($carriers as $c):?><option value="<?=(int)$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select><?php endif;?><input type="hidden" name="order_id" value="<?=(int)$r['id']?>"><input type="hidden" name="order_type" value="<?=e($r['order_type'])?>"><button name="update_status">Update</button></td><td><a href="order_details.php?order_id=<?=(int)$r['id']?>">View</a></td></form></tr><?php endwhile;?></table></div></body></html>
